version: '2'

volumes:
    dados:

services:
    db:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=Batatinha1Quando2Nasce3
        volumes:
            # Volume dos dados
            - dados:/var/lib/postgresql/data
            # Scripts
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    
    frontend:
        image: nginx:latest
        volumes:
            # Site
            - ./web:/usr/share/nginx/html
            # Configurações do proxy reverso
            # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        