# A nova imagem será baseada no nginx versão 1.13
FROM nginx:1.13

# Executa um comando dentro da imagem
# Substitui o arquivo index.html padrão do nginx por uma versão personalizada
RUN echo '<h1>Minha primeira imagem personalizada do Docker</h1>' > /usr/share/nginx/html/index.html

